### ISSUE TITLE
Tokenizer rewrite

### ISSUE THREAD

**Issue by rmind** [rmind/nxsearch#5]
Currently, the tokenizer is a quickly written naive implementation: 1) it is not efficient as it copies the whole input string; 2) it uses libc strtok_r() to replace the separator bytes with NIL terminator which may break UTF-8 strings.

Objective: write an efficient and UTF-8 compatible tokenizer, probably using a simple state machine, perhaps leveraging some UTF-8 helpers from the libicu Unicode library.

The new tokenizer should handle separators (dots, commas, etc) and other punctuation. Some cases to think about and consider:
- Basic punctuation: `foo, bar` producing `foo` and `bar` rather than `foo,` and `bar`.
- Brackets and marking: `the [client] is <...>`, `some *bold*` or `_underscore_` marks.
- Broken spacing: `Some.Text,which doesn't have spaces right;one;two;three.`.
- Dashes: `keep-alive`, `this--done` (m-dash stands for "is").
- [Optional] Corner cases: `U.S.A.`, `I.B.M.` or `Dennis M. Ritchie`.

**Comment by toloco** [comment]
We could use the Unicode text segmentation algorithm" see: https://unicode.org/reports/tr29/

**Comment by rmind** [comment]
@toloco: That is pretty much what we want. Please go ahead with the implementation!
